# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods integration for iOS
use_frameworks!
use_modular_headers!

# Flutter dependencies
flutter_application_path = '../'
raise_if_flutter_gems_plugins_missing = true
eval File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies'))

target 'Runner' do
  pod 'Firebase/Messaging', '~> 10.0'
  pod 'Firebase/Core', '~> 10.0'

  # iOS platform pods
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)

      # Deployment target
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

        # Fix Xcode 15 signing issue
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
      end
    end
  end
end

# Minimum iOS version
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
